// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SpedImporter.Infrastructure.Data;

#nullable disable

namespace SpedImporter.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260306154409_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("SpedImporter.Domain.Entities.Importacao", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("DataImportacaoUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("NomeArquivo")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("PeriodoFinal")
                        .HasMaxLength(8)
                        .HasColumnType("varchar(8)");

                    b.Property<string>("PeriodoInicial")
                        .HasMaxLength(8)
                        .HasColumnType("varchar(8)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<int>("TotalLinhas")
                        .HasColumnType("int");

                    b.Property<string>("VersaoLeiaute")
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.HasKey("Id");

                    b.ToTable("Importacoes", (string)null);
                });

            modelBuilder.Entity("SpedImporter.Domain.Entities.RegistroBruto", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("CodigoRegistro")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("Erro")
                        .HasColumnType("longtext");

                    b.Property<Guid>("ImportacaoId")
                        .HasColumnType("char(36)");

                    b.Property<string>("LinhaOriginal")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("NumeroLinha")
                        .HasColumnType("int");

                    b.Property<bool>("Processado")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("QuantidadeCampos")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CodigoRegistro");

                    b.HasIndex("ImportacaoId", "NumeroLinha");

                    b.ToTable("RegistrosBrutos", (string)null);
                });

            modelBuilder.Entity("SpedImporter.Domain.Entities.RegistroBruto", b =>
                {
                    b.HasOne("SpedImporter.Domain.Entities.Importacao", "Importacao")
                        .WithMany("Registros")
                        .HasForeignKey("ImportacaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Importacao");
                });

            modelBuilder.Entity("SpedImporter.Domain.Entities.Importacao", b =>
                {
                    b.Navigation("Registros");
                });
#pragma warning restore 612, 618
        }
    }
}
